### PR TITLE
Evr 125 fix broken use template

### LINKED ISSUE #7: create_document_from_template uses 2d fields array but API expects a plain array
I'm trying to create a document using template already setup in Eversign. When I call the method create_document_from_template (based on the example code in this repo) I receive the following error 

"Missing Field identifier for one or more fields"

** Steps to reproduce the behavior: **
1. Go to eversign and build a template with at least 1 merge field
2. Setup and call create_document_from_template and populate the field data on the document_template

**Expected behavior**
It should merge the field data and create a document in eversign

**Actual outcome**
It fails to create a document with "Missing Field identifier for one or more fields" error

**Additional context**
I'm using the code on master as the latest released gem does not support rails > 4.2 (which is pretty old). Rails version is 6.0.3.2

I have managed to get my calls to succeed using Postman after the sales team informed me that the fields array should be a single dimensional array rather than the 2d [[field1, field2]] the sdk seems to build. Obviously this isn't that useful as we want to use the SDK! 

thanks for any help

### PR DESCRIPTION
**Pull request by alexkhalevine**
fixes https://github.com/eversign/eversign-ruby-sdk/issues/7

- when creating a document from template, `fields` object should be 1 dimensional array.
- improved example `create_document_from_template.rb`
- added dot env config support

### CODE REVIEW

File: lib/eversign/client.rb [hunk 1]
```diff
@@ -1,207 +1,207 @@
...
+      get_documents("template_draft")
+    end
+
+    def get_document(document_hash)
+      path = "/api/document?access_key=#{access_key}&business_id=#{business_id}&document_hash=#{document_hash}"
+      response = execute_request(:get, path)
+      extract_response(response.body, Eversign::Mappings::Document)
+    end
+
+    def create_document(document, isFromTemplate = false)
```
Comment (alexkhalevine) [inline lib/eversign/client.rb:102]: differentiate if document is created from template, for later flattening the fields array
